import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'column',
  },
  editText: {
    backgroundColor: '#fff',
    borderWidth: 4,
    padding: 7,
    borderStyle: 'solid',
    borderColor: '#eedaea',
    fontSize: 20,
    fontFamily: 'JuaRegular',
    height: 250,
  },
  edit: {
    backgroundColor: '#fff',
    borderWidth: 4,
    padding: 7,
    borderStyle: 'solid',
    borderColor: '#eedaea',
    fontSize: 20,
    fontFamily: 'JuaRegular',
    height: 400,
  },
  text: {
    fontSize: 15,
    color: '#000',
    fontFamily: 'JuaRegular',
    textAlign: 'center',
  },
  caution: {
    height: 170,
    paddingTop: 10,
    alignItems: 'stretch',
    justifyContent: 'center',
  },
  btnAdd: {
    height: '10%',
    width: '100%',
    position: 'absolute',
    bottom: 0,
  },
  editHash: {
    padding: 10,
    fontSize: 15,
    flex: 1,
    fontFamily: 'JuaRegular',
    borderBottomWidth: 4,
    borderStyle: 'solid',
    borderColor: '#eedaea',
  },
  editTitle: {
    borderBottomWidth: 0,
    backgroundColor: '#fff',
    borderStyle: 'solid',
    borderColor: '#eedaea',
    borderWidth: 4,
    fontFamily: 'JuaRegular',
    padding: 10,
    fontSize: 26,
  },
  btnHash: {
    borderBottomWidth: 4,
    borderLeftWidth: 4,
    borderRightWidth: 4,
    height: 50,
    flex: 1,
    padding: 15,
    alignSelf: 'flex-end',
    borderStyle: 'solid',
    borderColor: '#eedaea',
  },
  containerRow: {
    flexDirection: 'row',
    display: 'flex',
  },
  hashItem: {
    backgroundColor: '#fff',
    marginLeft: 10,
    marginRight: 10,
    marginTop: 4,
    padding: 15,
    paddingRight: 3,
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  list: {
    flexGrow: 1,
  },
  icon: {
    left: 7,
    top: -14,
    position: 'relative',
  },
});

export default styles;
